version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    ports:
     - 3307:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - db:/var/lib/mysql


  achat_backend:
    image: safouenejebali/achat:1.0.0
    restart: on-failure
    ports:
     - 6868:8089
    depends_on:
     - mysqldb
    stdin_open: true
    tty : true
  
