version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE= achatdb
    ports:
      - 3307:3306
  achat-backend:
    depends_on:
      - mysqldb
    image: safouenejebali/achat:1.0.0
    restart: on-failure
    ports:
      - 6868:8089
    environment:
      SPRING_APPLICATION_JSON: '{
                    "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/achatdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
                    "spring.datasource.username" : "root",
                    "spring.datasource.password" : "",
                    "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
                    "spring.jpa.hibernate.ddl-auto" : "update"
            }'
    stdin_open: true
    tty: true

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - 9090:9090
    depends_on:
      - achat-backend
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - grafana-storage:/var/lib/grafana
volumes:
  db:
  grafana-storage:
  prometheus-data: