version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  achat-backend:
    depends_on:
      - mysqldb
    image: sahliakram/achat:1.0
    restart: on-failure
    ports:
      - 8089:8089
    stdin_open: true
    tty: true
volumes:
  db :
