version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  achat-backend:
    depends_on:
      - mysqldb
    image: nardine22/achat:1.0.0
    build: ./
    restart: on-failure
    ports:
      - 8089:8089
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
