version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      #- MYSQL_ROOT_PASSWORD=
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=achatdb
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  achat-backend:
    depends_on:
      - mysqldb
    image: aidlisalma/achat:1.0
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url=jdbc" : "mysql://mysqldb:3306/achatdb?createDatabaseIfNotExist=true",
      "spring.datasource.username" : "root",
      "spring.datasource.password" : "",
      "spring.jpa.show-sql" : "false",
      "spring.jpa.hibernate.ddl-auto" : "update",
      "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect" 
      }'

    stdin_open: true
    tty: true
volumes:
  db: