version: '2'
services:
  mysqldb:
    image: mysql:5.6
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: achatdb
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
  application:
    image: sahliakram/achat:1.0.0
    build: .
    restart: always
    depends_on:
      - mysqldb
    ports:
      - 8089:8089