version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: achatdb
      MYSQL_ROOT_HOST: 172.19.0.3
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - mynetwork

  achat-backend:
    depends_on:
      - mysqldb
    image: sahliakram/achat:1.0.0
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.1.6:3306/achatdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    stdin_open: true
    tty: true
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db:
