version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD:true
      - MYSQL_DATABASE=achat_db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  achat-backend:
    depends_on:
      - mysqldb
    image: nardine22/achat:1.0
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url=jdbc" : "mysql://mysql:3306/achatdb?creatteDatabaseIfNotExist=true",
      "spring.datasource.username" : "root",
      "spring.datasource.password" : null,
      "spring.jpa.show-sql" : "false",
      "spring.jpa.hibernate.ddl-auto" : "update"
      "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect" 
      }'

    stdin_open: true
    tty: true
volumes:
  db:
