version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE= achatdb
    ports:
      - 3307:3306
  achat-backend:
    depends_on:
      - mysqldb
    image: safouenejebali/achat:1.0.0
    restart: on-failure
    ports:
      - 6868:8089
    environment:
      SPRING_APPLICATION_JSON: '{
                    "spring.datasource.url"  : "jdbc:mysql://192.168.100.123:3306/achatdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
                    "spring.datasource.username" : "root",
                    "spring.datasource.password" : "",
                    "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
                    "spring.jpa.hibernate.ddl-auto" : "update"
            }'
    stdin_open: true
    tty: true
volumes:
  db: